language: c

compiler:
    - clang
    - gcc

script: ./demo/run-all --runtime=tot --compiler=simple --clean-build --time

os:
    - linux
    - osx

# No notifications for Linux until it's believed-working.
matrix:
    allow_failures:
        - os: linux
