#
# Project information
#

language: c

compiler:
  - clang
  - gcc

script: ./demo/run-all --runtime=tot --compiler=simple --clean-build --time


#
# Configurations to build
#

os:
  - linux
  - osx

matrix:
  # No notifications for Linux until it's believed-working.
  allow_failures:
    - os: linux
  # Don't bother with Gcc on OS X.
  exclude:
    - os: osx
      compiler: gcc


#
# Branches to build
#

branches:
  only:
    - master
