#!/bin/bash
#
# Copyright 2013-2014 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# General setup
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}

init-prog


#
# Argument parsing
#

# Output file name.
outputFile=''

# Did we get `--out-dir`?
gotOutDir=0

# Whether to compile to binary.
fullCompile='yes'

# Additional arguments passed to the program.
moreArgs=()

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        echo "${progName} [--output=<path>] [--c-code] [--mode=<mode>]"
        echo "    <source-path>"
        exit
    elif [[ ${opt} == '--c-code' ]]; then
        fullCompile='no'
    elif [[    ${opt} =~ ^--mode=
            || ${opt} =~ ^--in-dir= ]]; then
        moreArgs+=("${opt}")
    elif [[ ${opt} =~ ^--out-dir= ]]; then
        moreArgs+=("${opt}")
        gotOutDir=1
    elif [[ ${opt} =~ ^--output=(.*) ]]; then
        outputFile="${BASH_REMATCH[1]}"
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        exit 1
    else
        break
    fi
    shift
done
unset opt

if (( $# == 0 )); then
    echo 'Missing source file name.' 1>&2
    exit 1
elif (( $# > 1 || gotOutDir )); then
    # Multiple source files or `--out-dir` specified.
    fullCompile='no'
    if [[ ${outputFile} != '' ]]; then
        echo 'Cannot specify --output with multiple sources or --out-dir.' 1>&2
        exit 1
    fi
else
    # Single source file and no `--out-dir`.
    if [[ ${outputFile} == '' ]]; then
        if [[ ${fullCompile} == 'yes' ]]; then
            outputFile="${1%.sam*}.samb"
        else
            outputFile="${1%.sam*}.c"
        fi
    fi
fi

if [[ ${outputFile} == '-' || ${outputFile} == '/dev/stdout' ]]; then
    outputFile='/dev/stdout'
    fullCompile='no'
fi


#
# Main script
#

if [[ ${fullCompile} == 'yes' ]]; then
    compiledFile="${outputFile}"
    outputFile="${compiledFile}.c"
fi

if [[ ${outputFile} != '' ]]; then
    moreArgs+=("--output=${outputFile}")
fi

"${progDir}/samex" "${baseDir}/lib/${progName}" \
    "${moreArgs[@]}" -- "$@" \
|| exit 1

if [[ ${fullCompile} == 'yes' ]]; then
    "${progDir}/compile-samex-addon" --output="${compiledFile}" "${outputFile}"
fi
