#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Main script
#

CC=cc

# Note: The GNU equivalent to `-dynamiclib` seems to be `-shared`, and
# the equivalent to `-undefined dynamic_lookup` seems to be `-Ur`.
COMPILE_LIB=(
    "${CC[@]}"
        -dynamiclib -undefined dynamic_lookup
        -I"${baseDir}/../samizdat-0/include"
)

sourceFile="$1"
outputFile="$2"
intermedFile="${outputFile}.c"

"${baseDir}/samizdat-0/samizdat-0" "${progDir}" \
    "${sourceFile}" "${intermedFile}" \
|| exit 1

"${COMPILE_LIB[@]}" -o "${outputFile}" "${intermedFile}"
