#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Main script
#

projectName="$(basename "${progDir}")"
binNames=("bin/samex" "bin/compile-samex-addon" "helper/find-samex")

OUT="${OUT:-${baseDir}/out}"
FINAL="${OUT}/final"

for name in "${binNames[@]}"; do
    rm -f "${FINAL}/${name}"
    mkdir -p "${FINAL}/$(dirname "${name}")" || exit 1
    cp "${progDir}/${name}" "${FINAL}/${name}" || exit 1
done
