#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. See the associated file "LICENSE.md" for details.


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Main script
#

projectName="$(basename "${progDir}")"

OUT="${OUT:-${baseDir}/out}/${projectName}"
rm -rf "${OUT}" || exit 1
mkdir -p "${OUT}" || exit 1

COMPILE_C=(cc -g -c -I"${baseDir}/c-api")
LINK_BIN=(cc -g)

errors=0
for file in ${progDir}/*.c; do
    outFile="${OUT}/$(basename "${file}" .c).o"
    echo "${COMPILE_C[@]}" -o "${outFile}" "${file}"
    "${COMPILE_C[@]}" -o "${outFile}" "${file}" || (( errors++ ))
done

if (( errors != 0 )); then
    printf '%d error(s)\n' "${errors}"
    exit 1
fi

"${LINK_BIN[@]}" -o "${OUT}/${projectName}" \
    ${OUT}/*.o \
    ${OUT}/../sam-data-0/*.o \
    ${OUT}/../sam-exec-0/*.o \
|| exit 1
