#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. See the associated file "LICENSE.md" for details.


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Main script
#

projectName="$(basename "${progDir}")"

OUT="${OUT:-${baseDir}/out}/${projectName}"
rm -rf "${OUT}" || exit 1
mkdir -p "${OUT}" || exit 1

COMPILE_C=(cc -g -c -I"${progDir}")
LINK_BIN=(cc -g)

cd "${progDir}"

xxd -i "lib/library.sam0" > "lib/library-generated.c" || exit 1

SOURCES=($(find . -name '*.c'))

errors=0
for file in "${SOURCES[@]}"; do
    [[ ${file} =~ \./(.*)/([^/]*)\.c$ ]]
    dir="${BASH_REMATCH[1]}"
    baseName="${BASH_REMATCH[2]}"
    outDir="${OUT}/${dir}"
    outFile="${outDir}/${baseName}.o"
    echo "${COMPILE_C[@]}" -o "${outFile}" "${file}"
    mkdir -p "${outDir}"
    "${COMPILE_C[@]}" -o "${outFile}" "${file}" || (( errors++ ))
done

if (( errors != 0 )); then
    printf '%d error(s)\n' "${errors}"
    exit 1
fi

cd "${OUT}"
OBJECTS=($(find . -name '*.o'))
"${LINK_BIN[@]}" -o "${projectName}" "${OBJECTS[@]}" || exit 1
