#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Argument parsing
#

# Whether to compile for profiling.
profile='no'

# Whether to compile with optimiaztions on.
optimize='no'

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        echo "${progName} [--optimize] [--profile]"
        exit
    elif [[ ${opt} == '--optimize' ]]; then
        optimize='yes'
    elif [[ ${opt} == '--profile' ]]; then
        profile='yes'
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        exit 1
    else
        break
    fi
    shift
done
unset opt


#
# Main script
#

projectName="$(basename "${progDir}")"

OUT="${OUT:-${baseDir}/out}/${projectName}"
rm -rf "${OUT}" || exit 1
mkdir -p "${OUT}" || exit 1

if [[ ${profile} == 'yes' ]]; then
    CC=(cc -pg)
else
    CC=(cc)
fi

if [[ ${optimize} == 'yes' ]]; then
    CC=(${CC[@]} -O3)
fi

COMPILE_C=("${CC[@]}" -g -c -I"${progDir}/include")
LINK_BIN=("${CC[@]}" -g)
cd "${progDir}"

C_SOURCES=($(find . -name '*.c'))
LIB_SOURCES=($(find ../samizdat-0-lib -name '*.sam*'))

for file in "${LIB_SOURCES[@]}"; do
    inDir="$(dirname "${file}")"
    inFile="$(basename "${file}")"
    outFile="${OUT}/$(echo "${inFile}" | tr '.' '-').c"
    # `xxd` names its output after the full input path, hence the `cd`.
    (cd "${inDir}"; xxd -i "${inFile}" > "${outFile}") || exit 1
    C_SOURCES+=("${outFile}")
done

errors=0
for file in "${C_SOURCES[@]}"; do
    if [[ ${file} =~ ^\./(.*)/([^/]*)\.c$ ]]; then
        # It's a normal source file.
        dir="${BASH_REMATCH[1]}"
        baseName="${BASH_REMATCH[2]}"
        outDir="${OUT}/${dir}"
        infoName="${file}"
    else
        # It's a generated source file.
        [[ ${file} =~ ^"${OUT}"/(.*)\.c$ ]] || exit 1 # Assert file location.
        baseName="${BASH_REMATCH[1]}"
        infoName="${baseName}"
        outDir="${OUT}"
        infoName="${baseName}.c"
    fi

    outFile="${outDir}/${baseName}.o"
    mkdir -p "${outDir}"
    echo "Compile: ${infoName}"
    "${COMPILE_C[@]}" -o "${outFile}" "${file}" || (( errors++ ))
done

if (( errors != 0 )); then
    printf '%d error(s)\n' "${errors}"
    exit 1
fi

cd "${OUT}"
OBJECTS=($(find . -name '*.o'))
"${LINK_BIN[@]}" -o "${projectName}" "${OBJECTS[@]}" || exit 1
