#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Argument parsing
#

# Whether to compile for profiling.
profile='no'

# Whether to compile with optimiaztions on.
optimize='no'

# Name of executable to produce.
name='samex-naif'

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        echo "${progName} [--optimize] [--profile] [--name=<name>]"
        exit
    elif [[ ${opt} =~ ^--name=(.*) ]]; then
        name="${BASH_REMATCH[1]}"
    elif [[ ${opt} == '--optimize' ]]; then
        optimize='yes'
    elif [[ ${opt} == '--profile' ]]; then
        profile='yes'
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        exit 1
    else
        break
    fi
    shift
done
unset opt


#
# Main script
#

projectName="$(basename "${progDir}")"
binName='samex' # Name of executable in the `lib` directory.

OUT="${OUT:-${baseDir}/out}"
INTERMED="${OUT}/intermed/${projectName}"
FINAL="${OUT}/final"
FINAL_INCLUDE="${FINAL}/include/${name}"
FINAL_LIB="${FINAL}/lib/${name}"

rm -rf "${INTERMED}" "${FINAL_LIB}" "${FINAL_INCLUDE}" || exit 1
mkdir -p "${INTERMED}" || exit 1
mkdir -p "${FINAL_INCLUDE}" || exit 1
mkdir -p "${FINAL_LIB}" || exit 1

if [[ ${profile} == 'yes' ]]; then
    CC=(cc -pg)
else
    CC=(cc)
fi

if [[ ${optimize} == 'yes' ]]; then
    CC=(${CC[@]} -O3)
fi

COMPILE_C=("${CC[@]}" -g -c -I"${progDir}/include")
LINK_BIN=("${CC[@]}" -g)
cd "${progDir}"

C_SOURCES=($(find . -name '*.c'))
LIB_SOURCE_BASE="${progDir}/../samlib-naif"
LIB_SOURCES=($(cd "${LIB_SOURCE_BASE}"; find . -name '*.sam*'))

# Copies each library source file to the final lib directory.
for file in "${LIB_SOURCES[@]}"; do
    outFile="${FINAL_LIB}/corelib/${file}"
    mkdir -p "$(dirname "${outFile}")"
    cp "${LIB_SOURCE_BASE}/${file}" "${outFile}"
done

errors=0
for file in "${C_SOURCES[@]}"; do
    [[ ${file} =~ ^\./(.*)/([^/]*)\.c$ ]] || exit 1
    dir="${BASH_REMATCH[1]}"
    baseName="${BASH_REMATCH[2]}"
    outDir="${INTERMED}/${dir}"
    infoName="${file}"

    outFile="${outDir}/${baseName}.o"
    mkdir -p "${outDir}"
    echo "Compile: ${infoName}"
    "${COMPILE_C[@]}" -o "${outFile}" "${file}" || (( errors++ ))
done

if (( errors != 0 )); then
    printf '%d file(s) with error(s)\n' "${errors}"
    exit 1
fi

cd "${INTERMED}"
OBJECTS=($(find . -name '*.o'))
"${LINK_BIN[@]}" -o "${binName}" "${OBJECTS[@]}" || exit 1
cp "${binName}" "${FINAL_LIB}" || exit 1
cp -r "${progDir}/include"/* "${FINAL_INCLUDE}"
