<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sam</string>
		<string>sam0</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{ *(#.*)?$</string>
	<key>foldingStopMarker</key>
	<string>^[^{]*}[ ]*(#.*)?$</string>
	<key>name</key>
	<string>Samizdat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign</string>
			<key>match</key>
			<string>#.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
					<key>match</key>
					<string>\\([0nrt\\"]|x.*;)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>-?\b[0-9]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.other</string>
			<key>match</key>
			<string>@[_a-zA-Z][_a-zA-Z0-9]*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>\btrue\b|\bfalse\b|\bnull\b|\[\]|\[=\]|@@</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>&lt;&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>&lt;[_a-zA-Z][_a-zA-Z0-9]*&gt;</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{([^:{}@]*)(::)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(([_a-zA-Z0-9]*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_a-zA-Z][_a-zA-Z0-9]*) *(=)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.samizdat</string>
	<key>uuid</key>
	<string>6A87759F-F746-4E84-B7DB-AA5B49973202</string>
</dict>
</plist>
