#!/bin/bash
#
# Copyright 2014 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# General setup
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function initProg {
    local newp prog="$0"

    while newp="$(readlink "${prog}")"; do
        [[ ${newp} =~ ^/ ]] && prog="${newp}" || prog="${prog%/*}/${newp}"
    done

    progName="${prog##*/}"
    progDir="$(cd "${prog%/*}"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}

initProg
. "${progDir}/blur-utils.sh"


#
# Argument parsing
#

# Error flag.
error=0

# Directory to process.
dir='.'

# Whether to dump (print) rules before proceeding.
dump=0

# Spew option.
spewOption=()

# Options to pass through to the rules script.
rulesOpts=()

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        error='usage'
        break
    elif [[ ${opt} =~ ^--in-dir=(.*) ]]; then
        dir="${BASH_REMATCH[1]}"
    elif [[ ${opt} == --dump ]]; then
        dump=1
    elif [[ ${opt} =~ ^--quiet || ${opt} =~ ^--verbose=(.*) ]]; then
        spewOption=("${opt}")
    elif [[ ${opt} =~ ^-- ]]; then
        rulesOpts+=("${opt}")
    elif [[ ${opt} =~ ^-. ]]; then
        echo "Invalid option: ${opt}" 1>&2
        error=1
    else
        break
    fi
    shift
done
unset opt

# Targets (files or named ids).
targets=("$@")

if [[ ${#targets[@]} == 0 ]]; then
    # Default target.
    targets=(build)
fi

if [[ ${error} != 0 ]]; then
    echo 1>&2 "${progName} --help"
    echo 1>&2 "${progName} [--quiet | --verbose=<level>] [--dump]"
    echo 1>&2 "    [--in-dir=<dir>] [--<build-opt> ...] (target-file | id) ..."
    if [[ ${error} == 'usage' ]]; then
        error=0
    fi
    exit ${error}
fi


#
# Main script
#

# Find a blur rules script in the designated directory.

scriptName='blur.sh'
scriptPath="${dir}/${scriptName}"

if [[ ! (-f ${scriptPath} && -r ${scriptPath} ) ]]; then
    echo "No rules for directory: ${dir}" 1>&2
    exit 1
fi

cd "${dir}" # The rest of the script runs in the context of `dir`.

# Run the script, and collect output.

rules="$(
    PROJECT_NAME="${dir%/*}" \
    PROJECT_DIR="$(abs-path .)" \
    BASE_DIR="$(abs-path ..)" \
    BASH_ENV="${progDir}/blur-utils.sh" \
        bash -- "./${scriptName}" "${rulesOpts[@]}"
)"

if [[ $? != 0 ]]; then
    echo "Trouble generating rules." 1>&2
    exit 1
fi

if (( dump )); then
    printf '%s\n' "${rules}"
fi

# Run `blur-run`, passing it the rules.

printf '%s\n' "${rules}" | \
    "${progDir}/blur-run" "${spewOption[@]}" -- "${targets[@]}"
