#!/bin/bash
#
# Copyright 2014 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# General setup
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function initProg {
    local newp prog="$0"

    while newp="$(readlink "${prog}")"; do
        [[ ${newp} =~ ^/ ]] && prog="${newp}" || prog="${prog%/*}/${newp}"
    done

    progName="${prog##*/}"
    progDir="$(cd "${prog%/*}"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}

initProg
. "${progDir}/blur-utils.sh"


#
# Argument parsing
#

# Error flag.
error=0

# File to find rules in.
rulesFile='-'

# Verbosity level.
spew=1

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        error='usage'
    elif [[ ${opt} =~ ^--rules=(.*) ]]; then
        rulesFile="${BASH_REMATCH[1]}"
    elif [[ ${opt} =~ ^--quiet ]]; then
        spew=0
    elif [[ ${opt} =~ ^--verbose=(.*) ]]; then
        spew="${BASH_REMATCH[1]}"
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        error=1
    else
        break
    fi
    shift
done
unset opt

# Initial targets (files or named ids).
targets=("$@")

if [[ ${error} != 0 ]]; then
    echo 1>&2 "${progName} --help"
    echo 1>&2 "${progName} [--rules=<file>] [--quiet | --verbose=<level>]"
    echo 1>&2 "    (target-file | id) ..."
    if [[ ${error} == 'usage' ]]; then
        error=0
    fi
    exit ${error}
fi

if [[ ${rulesFile} == '-' ]]; then
    rulesFile='/dev/stdin'
fi


#
# Logging / spew
#

# Maximum line size, in columns. The double call is because redirecting
# stderr within a process substitution leaves `tput` without access to a
# terminal device to query. See <http://stackoverflow.com/questions/21763397>.
tput cols >/dev/null 2>&1 && MAX_COLS="$(tput cols)"
if [[ ${MAX_COLS} == '' ]]; then
    MAX_COLS=79
else
    (( MAX_COLS-- ))
fi

# Emit a status message.
function msg {
    local level=1

    if [[ $1 == '--err' ]]; then
        level=0
        shift
    elif [[ $1 == '--quiet' ]]; then
        level=-1
        shift
    elif [[ $1 == '--verbose' ]]; then
        level=2
        shift
    fi

    local line="$@"

    if (( level == -1 )); then
        # Only emit `quiet` messages on low spew levels.
        if (( spew >= 2 )); then
            return
        fi
    elif (( level > spew )); then
        # Message is out-of-range for current spew level.
        return
    fi

    if (( spew >= 2 )); then
        local i
        for (( i = 0; i < DEPTH; i++ )); do
            printf '  '
        done
    fi

    if (( spew <= 2 )); then
        local max=$(( MAX_COLS - DEPTH * 2 ))
        if (( ${#line} > max )); then
            local len=$(( (max - 5) / 2 ))
            if (( len < 20 )); then
                len=20
            fi
            line="${line:0:${len}} ... ${line:$(( ${#line} - len ))}"
        fi
    fi

    printf '%s\n' "${line}"
}

# Current depth
DEPTH=0

# Layer names.
LAYERS=()

# Increase status message depth.
function enterLayer {
    local name="$@"

    LAYERS[${DEPTH}]="${name}"
    msg --verbose ">> ${name}"

    (( DEPTH++ ))
}

# Decrease status message depth.
function leaveLayer {
    (( DEPTH-- ))

    local name="${LAYERS[${DEPTH}]}"
    unset LAYERS[${DEPTH}]

    msg --verbose "<< ${name}"
}

# Dump a layer trace.
function traceLayers {
    local i

    for (( i = DEPTH - 1; i >= 0; i-- )); do
        msg --err "...while in ${LAYERS[$i]}"
    done
}


#
# Helper functions
#

# Adds an association between a target and a rule number.
function addRuleToTarget {
    local rule="$1"
    local target="$2"

    local v="_rules$(mangle-string "${target}")"
    eval "${v}+=' ${rule}'"
}

# Outputs a sorted whitespace-separated list of all indices into `RULES`
# for rules associated with the given target. The target can be either a
# named id or a file. If it is a named id, then the result includes both
# rules directly tagged with the name as well as any other rules that target
# the targets of those rules.
function rulesFor {
    local target="$1"
    local v="_rules$(mangle-string "${target}")"

    if ! isId "${target}"; then
        # Easy case. It's a file.
        eval "echo \$${v}"
        return
    fi

    # It's an id. We have to find all other rules that have targets in
    # common with the already-selected rules.

    local -a rules handled
    local r anyMore=1

    # Initialize `rules`, such that `rules[x] == x` for each selected rule.
    for r in $(eval "echo \$${v}"); do
        rules[$r]="$r"
    done

    # Loop until transitive closure is found.
    while (( anyMore )); do
        anyMore=0
        # Iterate over the set indexes in `rules`.
        for r in "${!rules[@]}"; do
            if (( ${handled[$r]} )); then
                continue
            fi

            handled[$r]=1
            anyMore=1

            while read -r cmd rest; do
                case "${cmd}" in
                    (target)
                        for r in $(rulesFor "$(unquote "${rest}")"); do
                            rules[$r]="$r"
                        done
                        ;;
                esac
            done <<< "${RULES[${rules[$r]}]}"
        done
    done

    echo "${!rules[@]}"
}

# Indicates that the given word is a defined id.
function defineAsId {
    local id="$1"
    local v="_id$(mangle-string "${id}")"
    eval "${v}=yes"
}

# Exits success if the given word is a defined id.
function isId {
    local id="$1"
    local v="_id$(mangle-string "${id}")"
    local value="$(eval "echo \$${v:-no}")"

    if [[ ${value} == yes ]]; then
        return 0
    fi

    return 1
}

# Collects all the rules into the `RULES` array (one element per rule). This
# also canonicalizes the spacing of rules, so that there's no initial indent,
# and one space after the command. Finally, this also sets up the `IDS` array,
# which lists all named ids.
RULES=()
function rulesInit {
    local cmd rest curRule=()

    while read -r cmd rest; do
        [[ ${rest} == '' ]] \
            && curRule+=("${cmd}") || curRule+=("${cmd} ${rest}")
        case "${cmd}" in
            (rule-start)
                curRule=()
                ;;
            (rule-end)
                unset curRule[$((${#curRule[@]} - 1))]
                RULES+=("$(printf '%s\n' "${curRule[@]}")")
                curRule=()
                ;;
            (target)
                addRuleToTarget "${#RULES[@]}" "$(unquote-abs "${rest}")"
                ;;
            (id)
                local id=("$(unquote "${rest}")")
                defineAsId "${id}"
                addRuleToTarget "${#RULES[@]}" "${id}"
                ;;
        esac
    done < "${rulesFile}"
}

# Checks the given timestamps for newest req and oldest target. Returns
# true (0) if it indicates stale / missing targets.
function isStale {
    local newestReq="$1"
    local oldestTarget="$2"

    if (( newestReq < 0 || oldestTarget < 0 )); then
        # Either no reqs specified, no targets specified, or a nonexistent
        # target.
        return 0
    fi

    if (( newestReq > oldestTarget )); then
        # There is at least one req that is newer than one target.
        return 0
    fi

    # Nothing is stale, so exit false (failure).
    return 1
}

# Runs the given rule if any of:
# * it has no reqs
# * it has no targets
# * at least one target doesn't exist
# * at least one existing target has an older modification time than at least
#   one req
function runIfNeeded {
    # Split the rule into an array of lines.
    local rule=()

    local oldIfs="${IFS}"
    IFS=$'\n'
    rule=($1)
    IFS="${oldIfs}"

    local line cmd rest

    # Check asserts and moots.
    for line in "${rule[@]}"; do
        [[ ${line} =~ ^([^ ]*)(' ')?(.*)$ ]]
        cmd="${BASH_REMATCH[1]}"
        rest="${BASH_REMATCH[3]}"
        case "${cmd}" in
            (moot)
                rest="$(unquote "${rest}")"
                msg --verbose '??' "${rest}"
                bash -c "${rest}"
                if [[ $? == 0 ]]; then
                    # Moot test succeeded, which means that the rule doesn't
                    # need to execute anything.
                    return
                fi
                ;;
            (assert)
                rest="$(unquote "${rest}")"
                msg --verbose '!!' "${rest}"
                bash -c "${rest}"
                if [[ $? != 0 ]]; then
                    # Assert failed, which is a real error.
                    msg --quiet '!!' "${rest}"
                    msg --err "Assert failed."
                    traceLayers
                    return 1
                fi
                ;;
        esac
    done

    local newReqs=()   oldTargets=()
    local reqs=()      targets=()
    local newestReq=-1 oldestTarget=-1
    local inGroup=0 anyGroups=0 anyStale=0 stamp

    for line in "${rule[@]}"; do
        [[ ${line} =~ ^([^ ]*)(' ')?(.*)$ ]]
        cmd="${BASH_REMATCH[1]}"
        rest="${BASH_REMATCH[3]}"
        case "${cmd}" in
            (group-start)
                if (( inGroup )); then
                    msg --err "Group within group."
                    traceLayers
                    return 1
                elif [[ ${#reqs[@]} != 0 || ${#targets[@]} != 0 ]]; then
                    msg --err "Reqs or targets outside group."
                    traceLayers
                    return 1
                fi
                inGroup=1
                anyGroups=1
                ;;
            (group-end)
                if (( ! inGroup )); then
                    msg --err "Not in group."
                    traceLayers
                    return 1
                elif isStale "${newestReq}" "${oldestTarget}"; then
                    anyStale=1
                    newReqs+=("${reqs[@]}")
                    oldTargets+=("${targets[@]}")
                fi
                # Reset for further groups.
                reqs=()
                targets=()
                newestReq=-1
                oldestTarget=-1
                inGroup=0
                ;;
            (req)
                rest="$(unquote "${rest}")"
                if ! isId "${rest}"; then
                    rest="$(abs-path "${rest}")"
                    reqs+=("${rest}")
                    if [[ ! -e "${rest}" ]]; then
                        msg --err "Missing req: ${rest}"
                        traceLayers
                        return 1
                    elif [[ ! -d "${rest}" ]]; then
                        # Update req timestamp only if the req is *not* a
                        # directory. (Directory modtimes aren't really useful.)
                        stamp="$(mod-time "${rest}")"
                        if (( stamp > newestReq )); then
                            newestReq="${stamp}"
                        fi
                    fi
                fi
                ;;
            (target)
                rest="$(unquote-abs "${rest}")"
                targets+=("${rest}")
                if [[ ! -e "${rest}" ]]; then
                    # Missing target. Means that we need to run the rule
                    # (unless previously mooted).
                    oldestTarget=-1
                else
                    stamp="$(mod-time "${rest}")"
                    if (( oldestTarget == -1 || stamp < oldestTarget )); then
                        oldestTarget="${stamp}"
                    fi
                fi
                ;;
            (*)
                if (( inGroup )); then
                    msg --err "Invalid command in group: ${cmd}"
                    traceLayers
                    return 1
                fi
                ;;
        esac
    done

    # Handle reqs/targets that weren't part of a group.
    if (( anyGroups )); then
        if [[ ${#reqs[@]} != 0 || ${#targets[@]} != 0 ]]; then
            msg --err "Cannot mix grouped / ungrouped dependencies."
            traceLayers
            return 1
        fi
    elif isStale "${newestReq}" "${oldestTarget}"; then
        anyStale=1
        newReqs+=("${reqs[@]}")
        oldTargets+=("${targets[@]}")
    fi

    if (( ! anyStale )); then
        # Everything is up-to-date, and there is at least one req and one
        # target.
        return
    fi

    # Need to run the associated commands.

    if (( spew > 2 )); then
        local name

        if [[ ${#oldTargets[@]} != 0 ]]; then
            msg "Stale targets:"
            for name in "${oldTargets[@]}"; do
                msg "  ${name}"
            done
        fi

        if [[ ${#newReqs[@]} != 0 ]]; then
            msg "New reqs:"
            for name in "${newReqs[@]}"; do
                msg "  ${name}"
            done
        fi
    fi

    for line in "${rule[@]}"; do
        [[ ${line} =~ ^([^ ]*)(' ')?(.*)$ ]]
        cmd="${BASH_REMATCH[1]}"
        rest="${BASH_REMATCH[3]}"
        case "${cmd}" in
            (cmd)
                rest="$(unquote "${rest}")"
                msg --verbose '$$' "${rest}"
                bash -c "
                    STALE_TARGETS=($(quote "${oldTargets[@]}"))
                    NEW_REQS=($(quote "${newReqs[@]}"))
                    ${rest}"
                local status="$?"
                if [[ ${status} != 0 ]]; then
                    msg --quiet '$$' "${rest}"
                    msg --err "Non-zero exit status: ${status}"
                    traceLayers
                    return 1
                fi
                ;;
            (msg)
                rest="$(unquote "${rest}")"
                msg "${rest}"
                ;;
        esac
    done
}

# Attempts to satisfy the indicated target. The target can be either a file
# name or a named id. This works by finding all the reqs associated with
# the target, attempting (recursively) to satisfy them, and then running any
# commands associated with the target.
#
# If a target has already been satisfied at least once during this run,
# then it will not be tried again.
SATISFIED=()
PENDING=()
function satisfyTarget {
    local target="$1"
    local i

    if ! isId "${target}"; then
        target="$(abs-path "${target}")"
    fi

    for (( i = 0; i < ${#SATISFIED[@]}; i++ )); do
        if [[ ${target} == ${SATISFIED[$i]} ]]; then
            # The target has already been satisfied due to earlier activity.
            msg --verbose "<> ${target}"
            return
        fi
    done

    for (( i = 0; i < ${#PENDING[@]}; i++ )); do
        if [[ ${target} == ${PENDING[$i]} ]]; then
            # The target is already in the middle of being satisfied.
            msg --err "Recursive dependency on target: ${target}"
            traceLayers
            return 1
        fi
    done

    local rules=($(rulesFor "${target}"))

    if [[ ${#rules[@]} == 0 ]]; then
        if [[ ! -e "${target}" ]]; then
            msg --err "No rules defined for non-existent target: ${target}"
            traceLayers
            return 1
        else
            msg --verbose "== ${target}"
            return
        fi
    fi

    enterLayer "${target}"
    PENDING+=("${target}")

    local error=no

    for (( i = 0; i < ${#rules[@]}; i++ )); do
        if [[ ${error} == yes ]]; then
            break
        fi

        while read -r cmd rest; do
            if [[ ${cmd} == req ]]; then
                satisfyTarget "$(unquote "${rest}")"
                if [[ $? != 0 ]]; then
                    error=yes
                    break
                fi
            fi
        done <<< "${RULES[${rules[$i]}]}"
    done

    for (( i = 0; i < ${#rules[@]}; i++ )); do
        if [[ ${error} == yes ]]; then
            break
        fi

        runIfNeeded "${RULES[${rules[$i]}]}"
        if [[ $? != 0 ]]; then
            error=yes
        fi
    done

    leaveLayer

    SATISFIED+=("${target}")
    unset PENDING[$((${#PENDING[@]} - 1))]

    if [[ ${error} == yes ]]; then
        msg --err "Could not satisfy target: ${target}"
        traceLayers
        return 1
    fi
}


#
# Main script
#

rulesInit

for (( i = 0; i < ${#targets[@]}; i++ )); do
    satisfyTarget "${targets[$i]}"
    if [[ $? != 0 ]]; then
        exit 1
    fi
done
