#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Argument parsing
#

# Extra options to pass to `samex`.
samexOpts=()

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        echo "${progName} [--runtime=<name>]"
        echo '    [--build] [--optimize] [--time | --profile]'
        echo '    demo-name arg...'
        exit
    elif [[ ${opt} == '--build' || ${opt} == '--optimize'
        || ${opt} == '--profile' || ${opt} == '--time' ]]; then
        samexOpts+=("${opt}")
    elif [[ ${opt} =~ ^--runtime=(.*) ]]; then
        samexOpts+=("${opt}")
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        exit 1
    else
        break
    fi
    shift
done
unset opt

name="$1"
shift

if [[ ${name} == '' ]]; then
    echo 'Missing demo name.' 1>&2
fi


#
# Main script
#

# Find the demo directory, expanding from the given name if necessary.

if [[ ! ${name} =~ ^/ ]]; then
    names=($(find "${progDir}" -type d -name "${name}*"))
    case "${#names[@]}" in
        (0) echo "Not found: ${name}" 1>&2 ;;
        (1) : ;;
        (*) echo "Multiple matches: ${name}" 1>&2 ;;
    esac
    name="${names[0]}"
fi

# Ensure it's a readable directory .

if [[ ! (-r ${name} && -d ${name}) ]]; then
    echo "Not a readable directory: ${name}" 1>&2
    exit 1
fi

# Find the "main" and/or "module" file.

moduleFile="$(cd "${name}"; find . -maxdepth 1 -name 'module.sam')"
if [[ ${moduleFile} != '' ]]; then
    # If there's a module file, the path to pass is the directory.
    mainFile="."
else
    mainFile="$(cd "${name}"; find . -maxdepth 1 -name 'main.sam*')"
    if [[ ${mainFile} == '' ]]; then
        echo "No main or module file in directory: ${name}" 1>&2
        exit 1
    fi
fi

# Run it in the demo dir, passing it the main script name and any other
# arguments passed to this script.

cmd=("${baseDir}/out/final/bin/samex" "${samexOpts[@]}" "${mainFile}" "$@")

echo "Running demo: $(basename "${name}")"
cd "${name}"
echo '$' "${cmd[@]}"
echo ''
exec "${cmd[@]}"
