#!/bin/bash
#
# Copyright 2013-2014 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# General setup
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}

init-prog


#
# Argument parsing
#

# Build options.
buildOpts=()

# Runtime / compiler selection options.
runtimeOpts=()

while [[ $1 != '' ]]; do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--help' ]]; then
        echo "${progName} [--runtime=<name>] [--compiler=<mode>]"
        echo '    [--build] [--clean-build] [--no-optimize]'
        exit
    elif [[    ${opt} == '--build'
            || ${opt} == '--clean-build'
            || ${opt} == '--no-optimize' ]]; then
        buildOpts+=("${opt}")
    elif [[ ${opt} =~ ^--runtime= || ${opt} =~ ^--compiler= ]]; then
        runtimeOpts+=("${opt}")
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        exit 1
    else
        break
    fi
    shift
done
unset opt


#
# Main script
#

# Find all the demo directories.

allNames=($(cd "${progDir}"; find . -depth 1 -type d -exec basename '{}' ';'))

# Run each demo. For the first, pass it the appropriate build option(s) if
# so requested.

errorNames=()
for name in "${allNames[@]}"; do
    echo ''
    "${progDir}/run" "${buildOpts[@]}" "${runtimeOpts[@]}" "${name}"
    error="$?"
    if [[ ${error} != 0 ]]; then
        echo "Exited with error code: ${error}"
        errorNames+=("${name}")
    fi
    buildOpts=()
done

echo ''

if [[ ${#errorNames[@]} == 0 ]]; then
    echo 'All good!'
else
    echo 'Errors reported from:'
    for name in "${errorNames[@]}"; do
        echo "    ${name}"
    done
fi
