#!/bin/bash
#
# Copyright 2013 the Samizdat Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>


#
# Directory and program name detection
#

# Preserve the original working dir as origDir.
origDir="${PWD}"

# Set progName to the program name, progDir to its directory, and baseDir
# to progDir's directory. Follows symlinks.
prog="$0"
while [[ -h ${prog} ]]; do
    [[ "$(/bin/ls -ld "${prog}")" =~ .*' -> '(.*)$ ]]
    newProg="${BASH_REMATCH[1]}"
    if [[ ${newProg} =~ ^/ ]]; then
        prog="${newProg}"
    else
        prog="$(dirname "${prog}")/${newProg}"
    fi
done
progName="$(basename "${prog}")"
progDir="$(dirname "${prog}")"
cd "${progDir}"
progDir="${PWD}"
cd ..
baseDir="${PWD}"
cd "${origDir}"
unset prog
unset newProg


#
# Main script
#

projectName="$(basename "${progDir}")"

OUT="${OUT:-${baseDir}/out}/${projectName}"
rm -rf "${OUT}" || exit 1
mkdir -p "${OUT}" || exit 1

echo 'Build samizdat-0...'
"${baseDir}/samizdat-0/build" > /dev/null || exit 1
echo 'Done!'
echo ''

echo 'Build samizdat-1...'
cp -r ${progDir}/*.sam0 "${OUT}"
cp -r ${baseDir}/samizdat-0-lib "${OUT}"
chmod 755 ${OUT}/main.sam0
ln -s main.sam0 ${OUT}/samizdat-1
echo 'Done!'
echo ''
